from django.urls import path
from .views import *
from django.contrib.auth import views as viewsAuth

urlpatterns = [
    path('', index, name='index0'),
    path('discounts/', discounts, name='discounts0'),
    path('discount_delete/<int:pk>/', Discount_delete.as_view(),name='discount_delete0'),
    path('discount_update/<int:pk>/', Discount_update.as_view(),name='discount_update0'),
    path('discount_create/', Discount_create.as_view(),name='discount_create0'),
    path('management/', management, name='management0'),
    path('management/add/', CreateProduct.as_view(), name='create-product0'),
    path('management/makeup/', management_makeup, name='management-makeup0'),
    path('management/care-products/', management_careProducts, name='management-care0'),
    path('management/perfumes/', management_perfumes, name='management-perfumes0'),
    path('management/presents/', management_presents, name='management-presents0'),
    path('management/men-clothes/', management_men_clothes, name='management-men-clothes0'),
    path('management/women-clothes/', management_women_clothes, name='management-women-clothes0'),
    path('management/girls-clothes/', management_girls_clothes, name='management-girls-clothes0'),
    path('management/boys-clothes/', management_boys_clothes, name='management-boys-clothes0'),
    path('management/products/', search_products_management, name='search_products_management0'),
    path('management/users/', search_users_management, name='search_users_management0'),
    path('management/edit/<int:pk>/', UpdateProduct.as_view(), name='update_product0'),
    path('management/delete/<int:id>/', delete_product, name='delete_product0'),
    path('management/orders/<int:id>/', orders_product, name='orders_product0'),
    path('management/delete-user/<int:id>/', delete_user, name='delete-user0'),
    path('management/user/<int:id>/', user, name='user0'),
    path('register/', SignupViews.as_view(), name='register0'),
    path('register/login/', viewsAuth.LoginView.as_view(template_name='ar/auth/login.html', success_url='/ar/'), name='login0'),
    path('register/logout/', logoutViews, name='logout0'),
    path('register/change_password/', viewsAuth.PasswordChangeView.as_view(template_name='ar/auth/password_change.html', success_url='/ar/register/change_password/done/'), name='change-password0'),
    path('register/change_password/done/', viewsAuth.PasswordChangeDoneView.as_view(template_name='ar/auth/password_change_done.html'), name='password-change-done0'),
    path('search/', Search_products.as_view(), name='search_products0'),
    path('makeup/', makeup, name='makeup0'),
    path('care-products/', care_products, name='care-products0'),
    path('perfumes/', perfumes, name='perfumes0'),
    path('presents/', presents, name='presents0'),
    path('men-clothes/', men_clothes, name='men_clothes0'),
    path('women-clothes/', women_clothes, name='women_clothes0'),
    path('girls-clothes/', girls_clothes, name='girls_clothes0'),
    path('boys-clothes/', boys_clothes, name='boys_clothes0'),
    path('<int:id>/', detail, name='detail0'),
    path('orders/', orders, name='orders0'),
    path('order-delete/<int:id>/', order_delete, name='order_delete0'),
]
